# Imports

In [49]:
import pandas as pd
from pathlib import Path

from utils.config import OUT_DIR
SRC_ROOT = Path('').resolve().parents[1]
PARQUET_OUT_DIR = SRC_ROOT / OUT_DIR

# Dataframes loading

## Proceedings

In [50]:
df_proceedings = pd.read_parquet(PARQUET_OUT_DIR / 'proceedings.parquet')

In [51]:
df_proceedings.head()

   sitting                                              title
0        1  1. Posiedzenie Sejmu RP w dniach 13, 14, 21, 2...
1        2  2. Posiedzenie Sejmu RP w dniach 16 i 17 stycz...
2        3  3. Posiedzenie Sejmu RP w dniu 18 stycznia 202...
3        4  4. Posiedzenie Sejmu RP w dniach 25 i 26 stycz...
4        5  5. Posiedzenie Sejmu RP w dniach 7, 8 i 9 lute...

## Voting

In [52]:
df_votings = pd.read_parquet(PARQUET_OUT_DIR / 'votings.parquet')

In [53]:
df_votings.head()

,sitting,votingNumber,yes,no,abstain,totalVoted,date,kind,title,topic
0,1,NaN,458,0,0,NaN,2023-11-13T18:02:12,ELECTRONIC,Pkt. 2 Poselskie projekty uchwał w sprawie ust...,Pkt. 2 Poselskie projekty uchwał w sprawie ust...
1,1,NaN,272,27,153,NaN,2023-11-13T19:41:22,ELECTRONIC,Pkt. 3 Wybór Wicemarszałków Sejmu RP (druki nr...,Głosowanie nad kandydaturą Posła Krzysztofa Bo...
2,1,NaN,250,196,12,NaN,2023-11-13T19:42:14,ELECTRONIC,Pkt. 3 Wybór Wicemarszałków Sejmu RP (druki nr...,Głosowanie nad kandydaturą Posła Włodzimierza ...
3,1,NaN,257,185,16,NaN,2023-11-13T19:43:07,ELECTRONIC,Pkt. 3 Wybór Wicemarszałków Sejmu RP (druki nr...,Głosowanie nad kandydaturą Poseł Doroty Niedzi...
4,1,NaN,252,186,18,NaN,2023-11-13T19:43:53,ELECTRONIC,Pkt. 3 Wybór Wicemarszałków Sejmu RP (druki nr...,Głosowanie nad kandydaturą Poseł Moniki Wielic...

## Votes

In [54]:
df_votes = pd.read_parquet(PARQUET_OUT_DIR / 'votes.parquet')

In [55]:
df_votes.head()

   MP club vote  sitting  votingNumber
0 NaN  PiS  YES        1           NaN
1 NaN   KO  YES        1           NaN
2 NaN  PiS  YES        1           NaN
3 NaN  PiS  YES        1           NaN
4 NaN  PiS  YES        1           NaN

## Members

In [56]:
df_members = pd.read_parquet(PARQUET_OUT_DIR / 'members.parquet')

In [57]:
df_members.head()

   MP club firstName                lastName
0   1  PiS   Andrzej                Adamczyk
1   2   KO     Piotr               Adamowicz
2   3  PiS      Adam          Andruszkiewicz
3   4  PiS  Waldemar                  Andzel
4   5  PiS    Dorota  Arciszewska-Mielewczyk